name: Deploy #Название pipeline который будет выполнять github actions

on:
  push:
    branches:
      - staging # указываем название ветки в которую хотим пушить и запускать наш деплой

jobs:
  tests:
    name: Tests # название конктретной работы в pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # клонируем репозиторый
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

  deploy:
    name: Deploy
    needs: tests # указываем зависимую джобу т/е в данном случае деплой не запустится если тесты завершились ошибкой
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "../../build"
          target: ${{ secrets.PROJECT_PATH_TEST }}
